---
language: python
python: "2.7"
before_install:
 - sudo apt-get remove --purge fail2ban
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible==1.8.0
script:
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
  
